apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-get-secrets
  namespace: cloud-main-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-get-secrets
subjects:
- kind: ServiceAccount
  name: cnn-egress-gateway-debug-service-account
