apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  # Need to explicitly enable logging to stdout
  meshConfig:
    accessLogFile: /dev/stdout
  profile: minimal
  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: true
    - name: istio-egressgateway-cloudmain
      namespace: cloud-main-system
      enabled: true
      label:
        istio: istio-egressgateway-cloudmain
      # namespace: istio-system
      # k8s:
      #   # Horizontal Pod Autoscaling Settings
      #   hpaSpec:
      #     metrics:
      #     - resource:
      #         name: cpu
      #         targetAverageUtilization: 80
      #       type: Resource
      #     maxReplicas: 2
      #     minReplicas: 1
      #   # Service settings
      #   service:
      #     ports:
      #     - name: http2
      #       port: 80
      #       protocol: TCP
      #       targetPort: 8080
      #     - name: https
      #       port: 443
      #       protocol: TCP
      #       targetPort: 8443
      #     - name: ssh
      #       port: 22
      #       protocol: TCP
      #       targetPort: 8022
