apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: test-employee-notebook
  namespace: aaw-fc
spec:
  template:
    spec:
      containers:
      - image: k8scc01covidacr.azurecr.io/jupyterlab-cpu:16b01881
        imagePullPolicy: IfNotPresent
        name: test-employee-notebook
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi